### ISSUE TITLE
(39,31): A rest parameter must be of an array type.

### ISSUE THREAD

**Issue by debugging** [abeaudoin2013/react-beautiful-dnd-multi-list-typescript-example#1]
Hi! 

Just tried to get your repo running and ran into this type error when I ran npm start run:

```(39,31): A rest parameter must be of an array type.```

Any ideas?

**Comment by timjk** [comment]
@debugging I encountered the same issue, managed to resolve it by upgrading typescript to 3.x.x and renaming the interface Item to IItem.

(I would create a pr but encountered a lot of formatting changes, all the best :+1:)

**Comment by timjk** [comment]
@debugging turned off prettier and submitted a pr #2

**Comment by abeaudoin2013** [comment]
@timjk Thank you for submitting this PR! I have approved and merged! Closing this issue.
